name: Code Quality
run-name: ${{ github.actor }} is checking code quality üïµÔ∏è‚Äç‚ôÇÔ∏è
on:
  [workflow_call]:
    branches:
      - 'main'
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests
        shell: bash
  check-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Check linter
        run: uv run ruff check .
        shell: bash
      - name: Fix problems
        run: uv run ruff check --fix .
        shell: bash
  check-formatter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Check formatter
        run: uv run ruff format .
        shell: bash
  check-type-safety:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Check type safety
        run: uv run pyright
        shell: bash

