name: Deploying to Render
run-name: ${{ github.actor }} is deploying to Render ‚òÅ
on:
  [pull_request,push]:
    branches:
      - 'main'
jobs:
  deploy-to-render:
    runs-on: ubuntu-latest
    env:
      DEPLOY_WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL }}
      USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      SERVICENAME: ${{ vars.SERVICE_NAME }}
    steps:
      - name: Deploy with Hook
        run: curl "${DEPLOY_WEBHOOK_URL}&imgURL=docker.io%2F${USERNAMEL}%2F${SERVICENAME}%3Alatest"
        shell: bash