name: Create Docker Image
run-name: ${{ github.actor }} is pushing to registry üê≥
on:
  pull_request:
    branches:
      - 'main'
jobs:
  push-to-registry:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      DOCKERLOGIN: ${{ secrets.DOCKERHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build Docker Image
        run: docker build -t $USERNAME/dice-plus-1:latest .
      - name: Run Docker Container
        run: |
          docker ps
          docker run -p 10000:10000 $USERNAME/dice-plus-1
          docker ps

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the image to Docker Hub
        run: docker push $USERNAME/dice-plus-1:latest

