name: Create Docker Image
run-name: ${{ github.actor }} is pushing to registry üê≥
on:
  workflow_call:
jobs:
  quality:
    uses: ./.github/workflows/code-quality.yaml
  push-to-registry:
    needs: [quality]
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
      SERVICENAME: ${{  vars.SERVICE_NAME }}
    steps:
      - uses: actions/checkout@v5

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Build Docker Image
        run: docker build -t $USERNAME/$SERVICENAME:latest .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push the image to Docker Hub
        run: docker push $USERNAME/$SERVICENAME:latest

